/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reproductor;

import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author choko
 */
public class Ventana extends javax.swing.JFrame {
Reproductor r=null;
    public Ventana() {
        r=new Reproductor();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblfondo = new javax.swing.JLabel();
        btnstop = new javax.swing.JButton();
        btnplay = new javax.swing.JButton();
        btnresume = new javax.swing.JButton();
        btnpause = new javax.swing.JButton();
        cmbCanciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(946, 510));
        setMinimumSize(new java.awt.Dimension(946, 510));
        getContentPane().setLayout(null);
        getContentPane().add(lblfondo);
        lblfondo.setBounds(20, 20, 480, 430);

        btnstop.setBackground(new java.awt.Color(255, 153, 51));
        btnstop.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnstop.setText("■");
        btnstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstopActionPerformed(evt);
            }
        });
        getContentPane().add(btnstop);
        btnstop.setBounds(720, 270, 70, 49);

        btnplay.setBackground(new java.awt.Color(153, 255, 51));
        btnplay.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnplay.setText("►");
        btnplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplayActionPerformed(evt);
            }
        });
        getContentPane().add(btnplay);
        btnplay.setBounds(720, 160, 71, 54);

        btnresume.setBackground(new java.awt.Color(0, 204, 102));
        btnresume.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnresume.setText("♫►");
        btnresume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresumeActionPerformed(evt);
            }
        });
        getContentPane().add(btnresume);
        btnresume.setBounds(840, 270, 70, 50);

        btnpause.setBackground(new java.awt.Color(0, 153, 153));
        btnpause.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnpause.setText("ǁ");
        btnpause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpauseActionPerformed(evt);
            }
        });
        getContentPane().add(btnpause);
        btnpause.setBounds(840, 170, 66, 54);

        cmbCanciones.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        cmbCanciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Happier-Marshmello ft. Bastille(CDC´s)", "Brooks - Lynx", "Cash Cash - Overtime Vicetone Remix", "Happy Now-Kygo", "Cellopa-The Piano Guys" }));
        getContentPane().add(cmbCanciones);
        cmbCanciones.setBounds(600, 70, 320, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/nn (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 0, 970, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //cada try catch 
    private void btnstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstopActionPerformed
    try {
        r.Stop();
    } catch (Exception ex) {
        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
    lblfondo.setVisible(false);
    }//GEN-LAST:event_btnstopActionPerformed

    private void btnplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplayActionPerformed
    int i=cmbCanciones.getSelectedIndex();
    lblfondo.setVisible(true);
    String ruta;
    URL url;
    if(i==0){ 
        ruta="/Imagen/F.jpg";
        url=this.getClass().getResource(ruta);
        ImageIcon icon=new ImageIcon(url);
        lblfondo.setIcon(icon);
    try {
        r.AbrirFichero("/E:/reproductor/HappierCDC´s.mp3");
    } catch (Exception ex) {
        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    if(i==1){ 
        ruta="/Imagen/cancion2.jpg";
        url=this.getClass().getResource(ruta);
        ImageIcon icon=new ImageIcon(url);
        lblfondo.setIcon(icon);
    try {
        r.AbrirFichero("/E:/reproductor/Brooks - Lynx.mp3");
    } catch (Exception ex) {
        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    if(i==2){ 
        ruta="/Imagen/cancion3.jpg";
        url=this.getClass().getResource(ruta);
        ImageIcon icon=new ImageIcon(url);
        lblfondo.setIcon(icon);
    try {
        r.AbrirFichero("/E:/reproductor/Cash Cash.mp3");
    } catch (Exception ex) {
        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    if(i==3){ 
        ruta="/Imagen/cancion4.jpg";
        url=this.getClass().getResource(ruta);
        ImageIcon icon=new ImageIcon(url);
        lblfondo.setIcon(icon);
    try {
        r.AbrirFichero("/E:/reproductor/Happy Now.mp3");
    } catch (Exception ex) {
        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    if(i==4){ 
        ruta="/Imagen/cancion5.jpg";
        url=this.getClass().getResource(ruta);
        ImageIcon icon=new ImageIcon(url);
        lblfondo.setIcon(icon);
    try {
        r.AbrirFichero("/E:/reproductor/Celloopa.mp3");
    } catch (Exception ex) {
        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    }//GEN-LAST:event_btnplayActionPerformed

    private void btnpauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpauseActionPerformed
    try {
        r.Pausa();
    } catch (Exception ex) {
        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnpauseActionPerformed

    private void btnresumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresumeActionPerformed
    try {
        r.Continuar();
    } catch (Exception ex) {
        Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnresumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpause;
    private javax.swing.JButton btnplay;
    private javax.swing.JButton btnresume;
    private javax.swing.JButton btnstop;
    private javax.swing.JComboBox<String> cmbCanciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
